name: ab-tester
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - jinja2=2.11.2
  - pandas=1.3.4
  - pip=21.2.2
  - python=3.7.9
  - statsmodels=0.13.1
  - pip:
    - streamlit==1.8.1
